### PR TITLE
added off-for-timer to PT2262

### PR DESCRIPTION
**Pull request by hjgode**
Hello

I added the off-for-timer function to be able to switch a device off for x seconds

Please merge

Josef

### CODE REVIEW

**Comment by mdorenkamp** [comment]
is there a reason why you removed off-till?

**Comment by hjgode** [comment]
Uuups, no that was by mistake. I will change that back. I only need
off-for-timer but do not want to remove existing functions.

Sorry

Josef

**Comment by hjgode** [comment]
Changed back to code before my pull-request and generated a new one for off-for-timer in PT2262

**Comment by hjgode** [comment]
revert back to before my change and re-added off-for-timer to PT2262 again. Hopefully this time without mistakes.

**Pull request merged**
